// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using UIKit;

namespace AccountExecutiveApp.iOS
{
    partial class BorderedButton : UIButton
    {
        public BorderedButton() : base() { }

        public BorderedButton(IntPtr handle)
            : base(handle)
        {
        }

        public override void Draw(CGRect rect)
        {
            try
            {
                var path = UIBezierPath.FromRoundedRect(rect.Inset(1, 1), StyleGuideConstants.ButtonCornerRadius);
                CurrentTitleColor.SetStroke();
                path.Stroke();
            }
            catch (Exception)
            {
            }
        }

		public void Enable( bool enabled )
		{
			if (enabled)
				Hidden = false;
			else
				Hidden = true;
		}
    }
}
