// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AccountExecutiveApp.iOS
{
	public partial class Right : UITableViewCell
	{
		public Right (IntPtr handle) : base (handle)
		{
		}
	}
}
