// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace App2
{
	public partial class BorderedButton : UIButton
	{
		public BorderedButton (IntPtr handle) : base (handle)
		{
		}
	}
}
