//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiSystems.ClientApp.Web.Domain.MatchGuideService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Common")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecializationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecializationId {
            get {
                return this.SpecializationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecializationIdField, value) != true)) {
                    this.SpecializationIdField = value;
                    this.RaisePropertyChanged("SpecializationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EContractLoginResponse", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Contract")]
    [System.SerializableAttribute()]
    public partial class EContractLoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AEEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgreementSubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidatePaymentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SiSystems.ClientApp.Web.Domain.MatchGuideService.UserEContractPayrateDetailsRes[] ContractRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecializationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AEEmail {
            get {
                return this.AEEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.AEEmailField, value) != true)) {
                    this.AEEmailField = value;
                    this.RaisePropertyChanged("AEEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgreementSubId {
            get {
                return this.AgreementSubIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AgreementSubIdField, value) != true)) {
                    this.AgreementSubIdField = value;
                    this.RaisePropertyChanged("AgreementSubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateCompany {
            get {
                return this.CandidateCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateCompanyField, value) != true)) {
                    this.CandidateCompanyField = value;
                    this.RaisePropertyChanged("CandidateCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateName {
            get {
                return this.CandidateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateNameField, value) != true)) {
                    this.CandidateNameField = value;
                    this.RaisePropertyChanged("CandidateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidatePaymentType {
            get {
                return this.CandidatePaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidatePaymentTypeField, value) != true)) {
                    this.CandidatePaymentTypeField = value;
                    this.RaisePropertyChanged("CandidatePaymentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCompanyName {
            get {
                return this.ClientCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCompanyNameField, value) != true)) {
                    this.ClientCompanyNameField = value;
                    this.RaisePropertyChanged("ClientCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractEndDate {
            get {
                return this.ContractEndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractEndDateField, value) != true)) {
                    this.ContractEndDateField = value;
                    this.RaisePropertyChanged("ContractEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.UserEContractPayrateDetailsRes[] ContractRate {
            get {
                return this.ContractRateField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractRateField, value) != true)) {
                    this.ContractRateField = value;
                    this.RaisePropertyChanged("ContractRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractStartDate {
            get {
                return this.ContractStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractStartDateField, value) != true)) {
                    this.ContractStartDateField = value;
                    this.RaisePropertyChanged("ContractStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecializationId {
            get {
                return this.SpecializationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecializationIdField, value) != true)) {
                    this.SpecializationIdField = value;
                    this.RaisePropertyChanged("SpecializationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEContractPayrateDetailsRes", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Account")]
    [System.SerializableAttribute()]
    public partial class UserEContractPayrateDetailsRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NetPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetPay {
            get {
                return this.NetPayField;
            }
            set {
                if ((object.ReferenceEquals(this.NetPayField, value) != true)) {
                    this.NetPayField = value;
                    this.RaisePropertyChanged("NetPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayRate {
            get {
                return this.PayRateField;
            }
            set {
                if ((object.ReferenceEquals(this.PayRateField, value) != true)) {
                    this.PayRateField = value;
                    this.RaisePropertyChanged("PayRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateDesc {
            get {
                return this.RateDescField;
            }
            set {
                if ((object.ReferenceEquals(this.RateDescField, value) != true)) {
                    this.RateDescField = value;
                    this.RaisePropertyChanged("RateDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkValidationRes", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Account")]
    [System.SerializableAttribute()]
    public partial class LinkValidationRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserForgotPasswordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserLoginIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portal {
            get {
                return this.PortalField;
            }
            set {
                if ((object.ReferenceEquals(this.PortalField, value) != true)) {
                    this.PortalField = value;
                    this.RaisePropertyChanged("Portal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserForgotPasswordId {
            get {
                return this.UserForgotPasswordIdField;
            }
            set {
                if ((this.UserForgotPasswordIdField.Equals(value) != true)) {
                    this.UserForgotPasswordIdField = value;
                    this.RaisePropertyChanged("UserForgotPasswordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserLoginId {
            get {
                return this.UserLoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginIdField, value) != true)) {
                    this.UserLoginIdField = value;
                    this.RaisePropertyChanged("UserLoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetailsRes", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Account")]
    [System.SerializableAttribute()]
    public partial class UserDetailsRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecializationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InActive {
            get {
                return this.InActiveField;
            }
            set {
                if ((this.InActiveField.Equals(value) != true)) {
                    this.InActiveField = value;
                    this.RaisePropertyChanged("InActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortalType {
            get {
                return this.PortalTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PortalTypeField, value) != true)) {
                    this.PortalTypeField = value;
                    this.RaisePropertyChanged("PortalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecializationId {
            get {
                return this.SpecializationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecializationIdField, value) != true)) {
                    this.SpecializationIdField = value;
                    this.RaisePropertyChanged("SpecializationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/MatchGuide.BusinessObjects.Common")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchGuideService.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ClientLogin", ReplyAction="http://tempuri.org/IAccountService/ClientLoginResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ClientLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ClientLogin", ReplyAction="http://tempuri.org/IAccountService/ClientLoginResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ClientLoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Login", ReplyAction="http://tempuri.org/IAccountService/LoginResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Login", ReplyAction="http://tempuri.org/IAccountService/LoginResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ClientAutoLogin", ReplyAction="http://tempuri.org/IAccountService/ClientAutoLoginResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ClientAutoLogin(string userIDTSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ClientAutoLogin", ReplyAction="http://tempuri.org/IAccountService/ClientAutoLoginResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ClientAutoLoginAsync(string userIDTSID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CandidateLogin", ReplyAction="http://tempuri.org/IAccountService/CandidateLoginResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse CandidateLogin(string emailAddress, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/CandidateLogin", ReplyAction="http://tempuri.org/IAccountService/CandidateLoginResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> CandidateLoginAsync(string emailAddress, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/EContractCandidateLogin", ReplyAction="http://tempuri.org/IAccountService/EContractCandidateLoginResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.EContractLoginResponse EContractCandidateLogin(string emailAddress, string Password, string EContractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/EContractCandidateLogin", ReplyAction="http://tempuri.org/IAccountService/EContractCandidateLoginResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.EContractLoginResponse> EContractCandidateLoginAsync(string emailAddress, string Password, string EContractId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ForgotPassword", ReplyAction="http://tempuri.org/IAccountService/ForgotPasswordResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ForgotPassword(string emailAddress, string portal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/ForgotPassword", ReplyAction="http://tempuri.org/IAccountService/ForgotPasswordResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ForgotPasswordAsync(string emailAddress, string portal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/IsValidForgotPasswordLink", ReplyAction="http://tempuri.org/IAccountService/IsValidForgotPasswordLinkResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LinkValidationRes IsValidForgotPasswordLink(string forgotPasswordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/IsValidForgotPasswordLink", ReplyAction="http://tempuri.org/IAccountService/IsValidForgotPasswordLinkResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LinkValidationRes> IsValidForgotPasswordLinkAsync(string forgotPasswordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/UpdatePassword", ReplyAction="http://tempuri.org/IAccountService/UpdatePasswordResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse UpdatePassword(string forgotPasswordId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/UpdatePassword", ReplyAction="http://tempuri.org/IAccountService/UpdatePasswordResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> UpdatePasswordAsync(string forgotPasswordId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/SendOTP", ReplyAction="http://tempuri.org/IAccountService/SendOTPResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse SendOTP(string portal, string emailAddress, string userAgent, string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/SendOTP", ReplyAction="http://tempuri.org/IAccountService/SendOTPResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> SendOTPAsync(string portal, string emailAddress, string userAgent, string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/VerifyOTP", ReplyAction="http://tempuri.org/IAccountService/VerifyOTPResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes VerifyOTP(string portal, string emailAddress, string userAgent, string platform, string otpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/VerifyOTP", ReplyAction="http://tempuri.org/IAccountService/VerifyOTPResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes> VerifyOTPAsync(string portal, string emailAddress, string userAgent, string platform, string otpCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/VerifyOTPValidity", ReplyAction="http://tempuri.org/IAccountService/VerifyOTPValidityResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes VerifyOTPValidity(string portal, string emailAddress, string userAgent, string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/VerifyOTPValidity", ReplyAction="http://tempuri.org/IAccountService/VerifyOTPValidityResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes> VerifyOTPValidityAsync(string portal, string emailAddress, string userAgent, string platform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Logout", ReplyAction="http://tempuri.org/IAccountService/LogoutResponse")]
        SiSystems.ClientApp.Web.Domain.MatchGuideService.ServiceResponse Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Logout", ReplyAction="http://tempuri.org/IAccountService/LogoutResponse")]
        System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.ServiceResponse> LogoutAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : global::SiSystems.ClientApp.Web.Domain.MatchGuideService.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<global::SiSystems.ClientApp.Web.Domain.MatchGuideService.IAccountService>, global::SiSystems.ClientApp.Web.Domain.MatchGuideService.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ClientLogin(string userName, string password) {
            return base.Channel.ClientLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ClientLoginAsync(string userName, string password) {
            return base.Channel.ClientLoginAsync(userName, password);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ClientAutoLogin(string userIDTSID) {
            return base.Channel.ClientAutoLogin(userIDTSID);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ClientAutoLoginAsync(string userIDTSID) {
            return base.Channel.ClientAutoLoginAsync(userIDTSID);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse CandidateLogin(string emailAddress, string Password) {
            return base.Channel.CandidateLogin(emailAddress, Password);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> CandidateLoginAsync(string emailAddress, string Password) {
            return base.Channel.CandidateLoginAsync(emailAddress, Password);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.EContractLoginResponse EContractCandidateLogin(string emailAddress, string Password, string EContractId) {
            return base.Channel.EContractCandidateLogin(emailAddress, Password, EContractId);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.EContractLoginResponse> EContractCandidateLoginAsync(string emailAddress, string Password, string EContractId) {
            return base.Channel.EContractCandidateLoginAsync(emailAddress, Password, EContractId);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse ForgotPassword(string emailAddress, string portal) {
            return base.Channel.ForgotPassword(emailAddress, portal);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> ForgotPasswordAsync(string emailAddress, string portal) {
            return base.Channel.ForgotPasswordAsync(emailAddress, portal);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LinkValidationRes IsValidForgotPasswordLink(string forgotPasswordId) {
            return base.Channel.IsValidForgotPasswordLink(forgotPasswordId);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LinkValidationRes> IsValidForgotPasswordLinkAsync(string forgotPasswordId) {
            return base.Channel.IsValidForgotPasswordLinkAsync(forgotPasswordId);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse UpdatePassword(string forgotPasswordId, string newPassword) {
            return base.Channel.UpdatePassword(forgotPasswordId, newPassword);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> UpdatePasswordAsync(string forgotPasswordId, string newPassword) {
            return base.Channel.UpdatePasswordAsync(forgotPasswordId, newPassword);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse SendOTP(string portal, string emailAddress, string userAgent, string platform) {
            return base.Channel.SendOTP(portal, emailAddress, userAgent, platform);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.LoginResponse> SendOTPAsync(string portal, string emailAddress, string userAgent, string platform) {
            return base.Channel.SendOTPAsync(portal, emailAddress, userAgent, platform);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes VerifyOTP(string portal, string emailAddress, string userAgent, string platform, string otpCode) {
            return base.Channel.VerifyOTP(portal, emailAddress, userAgent, platform, otpCode);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes> VerifyOTPAsync(string portal, string emailAddress, string userAgent, string platform, string otpCode) {
            return base.Channel.VerifyOTPAsync(portal, emailAddress, userAgent, platform, otpCode);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes VerifyOTPValidity(string portal, string emailAddress, string userAgent, string platform) {
            return base.Channel.VerifyOTPValidity(portal, emailAddress, userAgent, platform);
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.UserDetailsRes> VerifyOTPValidityAsync(string portal, string emailAddress, string userAgent, string platform) {
            return base.Channel.VerifyOTPValidityAsync(portal, emailAddress, userAgent, platform);
        }
        
        public SiSystems.ClientApp.Web.Domain.MatchGuideService.ServiceResponse Logout() {
            return base.Channel.Logout();
        }
        
        public System.Threading.Tasks.Task<SiSystems.ClientApp.Web.Domain.MatchGuideService.ServiceResponse> LogoutAsync() {
            return base.Channel.LogoutAsync();
        }
    }
}
