// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ConsultantApp.iOS
{
	public partial class AddTimeEntryViewController : UIViewController
	{
		public AddTimeEntryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
