// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace ConsultantApp.iOS
{
	public partial class BorderedButton : UIButton
	{
		public BorderedButton (IntPtr handle) : base (handle)
		{
		}
	}
}
